<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>StardewEventTracker</AssemblyName>
    <RootNamespace>StardewEventTracker</RootNamespace>
    <Version>1.1.1</Version>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EnableHarmony>false</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- provided by SMAPI at runtime, so don't bundle it -->
    <Reference Include="Newtonsoft.Json" HintPath="$(GamePath)/smapi-internal/Newtonsoft.Json.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="LICENSE" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
